server:
  port: 11001

# 开启debug模式日志
debug: true

mybatis-plus:
  configuration:
    # 日志输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  # 将Druid设置为数据库连接池技术
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.106.122.140:3306/cloud_user?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: Lingling1314~
    
feign:
  httpclient:
    # 开启 feign 对 HttpClient连接池的使用
    enabled: true
    # 最大连接数
    max-connections: 200
    # 每个路径的最大连接数
    max-connections-per-route: 50